### PR TITLE
Mayhem Heroes Integration

### PR DESCRIPTION
**Pull request by capuanob**
Initial PR

### CODE REVIEW

**Review by xansec — APPROVED** [review]
LGTM!

**Comment by xansec** [comment]
@capuanob This seems to be failing, can you take a look?
https://github.com/mayhemheroes/ciscoconfparse/actions/runs/4135063050/jobs/7147041091

**Comment by capuanob** [comment]
> @capuanob This seems to be failing, can you take a look? https://github.com/mayhemheroes/ciscoconfparse/actions/runs/4135063050/jobs/7147041091

@xansec I can't open the Mayhem link, insufficient read permissions. Can I get access?

**Comment by xansec** [comment]
Added!

**Comment by capuanob** [comment]
@xansec Should be fixed! Seems new changes raise a ValueError way too quick for fuzzing to recognize as successful.

**Comment by xansec** [comment]
Thank you. Can you submit another PR with your fixes?

**Comment by capuanob** [comment]
@xansec Sure thing, just submitted. Apologize for the delay

**Pull request merged**
